-- COLLECTIONS IN PLSQL.
-- INDEX BY TABLE COLLECTION.

SET SERVEROUTPUT ON; 

DECLARE
TYPE SAL IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
CURSOR SAL_CUR IS SELECT * FROM (SELECT SALARY FROM EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM <= 5;
S SAL;
i NUMBER:=1;
BEGIN
OPEN SAL_CUR;
LOOP FETCH SAL_CUR INTO S(i);
EXIT WHEN SAL_CUR%NOTFOUND;
DBMS_OUTPUT.PUT_LINE(S(i));
i:=i+1;
END LOOP;
CLOSE SAL_CUR;
END;
/

-- NESTED TABLE COLLECTION.
DECLARE
TYPE SAL_TYPE IS TABLE OF NUMBER;
SAL SAL_TYPE:=SAL_TYPE();
CURSOR EMP_CUR IS SELECT SALARY FROM EMPLOYEES ORDER BY SALARY DESC;
BEGIN
FOR i IN EMP_CUR LOOP
SAL.EXTEND;
SAL(SAL.LAST):=i.SALARY;
END LOOP;
DBMS_OUTPUT.PUT_LINE('###############');
DBMS_OUTPUT.PUT_LINE('EXECUTE SUCCESSFULLY!!');
END;
/