-- DENSE_RANK()
-- UNLIKE RANK() WHICH SKIPS THE RANK NUMBER WHEN REPEATED ROWS COME, DENSE_RANK FUNCTION IS USED TO GIVE CONSECTIVE NUMBER TO EACH UNIQUE ROW AND KEEP REPEATED ROWS ON THE SAME RANK.
-- LET'S ASSUME A COLUMN THAT HAS TWO OR MORE ROWS WITH REPEATED VALUES ON WHICH RANK IS TO BE APPLIED.
-- BUT IF RANK() IS APPLIED, TWO ROWS WITH REPEATED VALUES WILL HAVE SAME RANK WHICH IS NOW TO BE RETIFIED WITH DENSE_RANK().
-- IT ALSO HAS TWO WAYS TO WRITE LIKE RANK(), AGGREGATE AND ANALYTIC.

-- DENSE_RANK() AGGREGATE FUNCTION

/*
DENSE_RANK(expr [, expr ]...) WITHIN GROUP
  (ORDER BY expr [ DESC | ASC ]
                 [ NULLS { FIRST | LAST } ]
            [,expr [ DESC | ASC ]
                   [ NULLS { FIRST | LAST } ]
            ]...
  )
*/

SELECT DENSE_RANK(15500, .05) WITHIN GROUP 
  (ORDER BY salary DESC, commission_pct) "Dense Rank" 
  FROM employees;

-- DENSE_RANK() OVER() ANALYTIC FUNCTION

/*
DENSE_RANK( ) OVER([ query_partition_clause ] order_by_clause)
*/

SELECT SALARY, DENSE_RANK() OVER(ORDER BY SALARY DESC) RANK_OVER_SAL
FROM EMPLOYEES
WHERE ROWNUM <= 5;
