SET SERVEROUTPUT ON;

-- EXPECTION IN PLSQL TO HANDLE VOILATION IN THE CODE OR PLSQL PROGRAM.
-- EXCEPTIONS CAN BE HANDLED BY THE PREDEFINED EXCEPTIONS THAT RAISED BY THE ORACLE.
-- IF EXCEPTION IS NOT FOUND IN PREDEFINED(ORACLE PROVIDED) LIBRARY THEN CREATE  YOUR OWN EXCEPTION.
-- ORACLE PROVIDES ERROR CODE, ERROR MSG TIED WITH EACH ERROR OCCURED, USE PRAGMA COMPILER TO INITIALISE USER DEFINED ERROR.

-- PREDEFINED ERROR HANDLING.
CREATE OR REPLACE PROCEDURE PRO_EXEC(EMP_ID NUMBER)
IS
REC EMPLOYEES%ROWTYPE;
BEGIN
SELECT * INTO REC FROM EMPLOYEES WHERE EMPLOYEE_ID = EMP_ID;

EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('RECORD NOT FOUND');
END;
/

EXEC PRO_EXEC(600);

-- USER DEFINED ERROR HANDLING.

CREATE OR REPLACE PROCEDURE PRO_EXEC(EMP_ID NUMBER)
IS
REC EMPLOYEES%ROWTYPE;
PRO_EXCEPTION EXCEPTION;
BEGIN
IF EMP_ID = 0 THEN
RAISE PRO_EXCEPTION;

ELSE
SELECT * INTO REC FROM EMPLOYEES WHERE EMPLOYEE_ID = EMP_ID;
END IF;

EXCEPTION
WHEN PRO_EXCEPTION THEN
DBMS_OUTPUT.PUT_LINE('RECORD NOT FOUND');
END;
/

EXEC PRO_EXEC(100);