SET SERVEROUTPUT ON;
-- FUNCTION IN PLSQL.
-- LIKE PROCEDURE, IT'S ALSO A STORED PROGRAM THAT HAVE A NAME AND CAN BE CALLED MANY TIMES WITH OR WITHOUT PARAMETERS
-- BUT FUNCTION MUST RETURN A VALUE WHILE PROCEDURE MAY OR MAY NOT.
CREATE OR REPLACE FUNCTION SAL_INCR(EMP_ID NUMBER)
RETURN NUMBER
IS
SAL NUMBER;
BEGIN
SELECT SALARY INTO SAL FROM EMPLOYEES
WHERE EMPLOYEE_ID = EMP_ID;

SAL:= SAL+SAL*3/100;

RETURN SAL;

END;
/ 

SELECT MATH_FUN(100) FROM DUAL;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID = 100;

--  TO RETURN A COLLECTION WITH PLSQL FUNCTION.
CREATE OR REPLACE TYPE TEST IS TABLE OF VARCHAR(500);
/

CREATE OR REPLACE FUNCTION TEST2 (ID INT)
RETURN TEST
IS
TT_T TEST;
BEGIN

SELECT FIRST_NAME
BULK COLLECT INTO TT_T
FROM EMPLOYEES
where DEPARTMENT_ID=ID;

RETURN TT_T;
END;
/

SELECT TEST2(30) EMPLOYEES_UNDER_DEPT30 FROM DUAL;