SET SERVEROUTPUT ON;
-- FUNCTION IN PLSQL.
-- LIKE PROCEDURE, IT'S ALSO A STORED PROGRAM THAT HAVE A NAME AND CAN BE CALLED MANY TIMES WITH OR WITHOUT PARAMETERS
-- BUT FUNCTION MUST RETURN A VALUE WHILE PROCEDURE MAY OR MAY NOT.
CREATE OR REPLACE FUNCTION SAL_INCR(EMP_ID NUMBER)
RETURN NUMBER
IS
SAL NUMBER;
BEGIN
SELECT SALARY INTO SAL FROM EMPLOYEES
WHERE EMPLOYEE_ID = EMP_ID;

SAL:= SAL+SAL*3/100;

RETURN SAL;

END;
/ 

SELECT MATH_FUN(100) FROM DUAL;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID = 100;

