-- STORED PROCEDURE IN PLSQL
CREATE OR REPLACE PROCEDURE PRO_NAME
IS
BEGIN
NULL;
END;
/

EXEC PRO_NAME;

-- YOU ARE ASKED TO CREATE A PROGRAM TO DISPLAY A SPECIFIC EMPLOYEE'S SALARY THAT USER WILL ENTER.
-- PROCEDURE WITH INPUT PARAMETER.
CREATE OR REPLACE PROCEDURE PRO_NAME(EID NUMBER)
IS
SAL NUMBER;
BEGIN
SELECT SALARY INTO SAL FROM EMPLOYEES WHERE EMPLOYEE_ID = EID;
DBMS_OUTPUT.PUT_LINE('EMPLOYEE: ENAME ' || SAL);
END;
/

SET SERVEROUTPUT ON;

EXEC PRO_NAME(100);

-- PROCEDURE WITH OUTPUT PARAMETER.
CREATE OR REPLACE PROCEDURE PRO_NAME(EID NUMBER, SAL OUT NUMBER)
IS
BEGIN
SELECT SALARY INTO SAL FROM EMPLOYEES WHERE EMPLOYEE_ID = EID;
DBMS_OUTPUT.PUT_LINE('OUTPUT PROCEDURE EXECUTED SUCCESSFULLY');
END;
/

DECLARE 
OUTP NUMBER;
BEGIN
PRO_NAME(100, OUTP);
DBMS_OUTPUT.PUT_LINE('EMP_NAME: ' ||OUTP);
END;
/

-- PROCEDURE WITH INPUT, OUTPUT, INOUT PARAMATERS.
CREATE OR REPLACE PROCEDURE PRO_NAME(EID NUMBER, SAL OUT NUMBER, ENAME IN OUT VARCHAR2)
IS
BEGIN
SELECT SALARY,FIRST_NAME||'_'||LAST_NAME INTO SAL,ENAME FROM EMPLOYEES WHERE EMPLOYEE_ID = EID;
DBMS_OUTPUT.PUT_LINE('OUTPUT PROCEDURE EXECUTED SUCCESSFULLY');
END;
/

DECLARE
OUTP NUMBER;
ENM VARCHAR2(50):= 'Steven';
BEGIN
PRO_NAME(100, OUTP, ENM);
DBMS_OUTPUT.PUT_LINE(ENM || ': ' || OUTP);
END;
/





