-- RANK() OVER() ANALYTIC FUNCTION
-- HERE YOU WILL FIND OUT A LIST OF 5 HIGHEST SALARIES IN THE DB TABLE.

/*
RANK( )
   OVER ([ query_partition_clause ] order_by_clause)
*/

SELECT SALARY, RANK() OVER(ORDER BY SALARY DESC) RANK_OVER_SAL
FROM EMPLOYEES
WHERE ROWNUM <= 5;


