-- RANK() CAN BE USED IN TWO WAYS IN ORACLE SQL QUERY.`
-- AS AN AGGREGATE FUNCTION AND AN ANALYTIC FUNCTION.
-- AGGREGATE RETURNS ONLY ONE ROW, ON THE OTHER HAND ANALYTIC RANK CAN RETURN MORE ROWS THAT SATIFY SEARCH CONDITION.

-- RANK() AGGREGATE FUNCTION
-- SUPPOSE YOU NEED TO FIND OUT THE RANK OF A SPECIFIC SALARY IN DB TABLE.
/*
RANK(expr [, expr ]...) WITHIN GROUP
   (ORDER BY
    expr [ DESC | ASC ]
         [ NULLS { FIRST | LAST } ]
    [, expr [ DESC | ASC ]
            [ NULLS { FIRST | LAST } ]
    ]...
   )
*/

SELECT RANK (2800) WITHIN GROUP
(ORDER BY SALARY) RANK_SAL FROM EMPLOYEES;




